using System;
using System.Collections.Generic;

namespace Rootborn.Game.Common
{
    /// <summary>
    /// Generated from lean JSON; do not edit by hand.
    /// Source: docs/art/modern-ui-style2-icon-catalog-gemini-lean.json
    /// </summary>
    public static class ModernUiStyle2IconCatalog
    {
        private const string Prefix = "ModernUI_16_Style2_";

        public static readonly IReadOnlyList<Entry> Entries = new[]
        {
            EntryFor(ModernUiStyle2Icon.PanelCornerTopLeftR0C0, 0, 0, "panel.cornerTopLeft", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelEdgeTopR0C1, 0, 1, "panel.edgeTop", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCornerTopRightR0C2, 0, 2, "panel.cornerTopRight", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelInnerLightR0C7, 0, 7, "panel.innerLight", "panel", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphQuestionMarkRedR0C16, 0, 16, "glyph.questionMark", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemGiftBoxGreenR0C17, 0, 17, "item.giftBox", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemGiftBoxRedR0C18, 0, 18, "item.giftBox", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphLightBulbOnR0C20, 0, 20, "glyph.lightBulb", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemEraserBlueR0C21, 0, 21, "item.eraser", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBagBrownR0C22, 0, 22, "item.bag", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSettingsGearR0C24, 0, 24, "glyph.settings", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCheckThinR0C25, 0, 25, "glyph.check", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphXMarkThinR0C26, 0, 26, "glyph.xMark", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCheckboxEmptyR0C27, 0, 27, "glyph.checkbox", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCheckboxCheckedR0C28, 0, 28, "glyph.checkbox", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphVolumeHighR0C30, 0, 30, "glyph.volume", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphVolumeLowR0C31, 0, 31, "glyph.volume", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphVolumeMutedR0C32, 0, 32, "glyph.volume", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.DirectionDownArrowSmallR0C33, 0, 33, "direction.downArrow", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCapsuleLeftR0C34, 0, 34, "panel.capsuleLeft", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCapsuleMiddleR0C35, 0, 35, "panel.capsuleMiddle", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCapsuleRightR0C36, 0, 36, "panel.capsuleRight", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelSquareOutlineR0C37, 0, 37, "panel.squareOutline", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonLockNormalR0C40, 0, 40, "button.lock", "button", "confirmed", "button.lock.state.r0", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonLockHoverR0C41, 0, 41, "button.lock", "button", "confirmed", "button.lock.state.r0", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonLockPressedR0C42, 0, 42, "button.lock", "button", "confirmed", "button.lock.state.r0", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonGridNormalR0C43, 0, 43, "button.grid", "button", "confirmed", "button.grid.state.r0", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonGridHoverR0C44, 0, 44, "button.grid", "button", "confirmed", "button.grid.state.r0", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonGridPressedR0C45, 0, 45, "button.grid", "button", "confirmed", "button.grid.state.r0", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonBackArrowNormalR0C46, 0, 46, "button.backArrow", "button", "confirmed", "button.backArrow.state.r0", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonBackArrowHoverR0C47, 0, 47, "button.backArrow", "button", "confirmed", "button.backArrow.state.r0", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonBackArrowPressedR0C48, 0, 48, "button.backArrow", "button", "confirmed", "button.backArrow.state.r0", "pressed"),
            EntryFor(ModernUiStyle2Icon.PanelEdgeLeftR1C0, 1, 0, "panel.edgeLeft", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelInnerLightR1C1, 1, 1, "panel.innerLight", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelEdgeRightR1C2, 1, 2, "panel.edgeRight", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.RibbonLeftR1C4, 1, 4, "ribbon.left", "ribbon", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.RibbonMiddleR1C5, 1, 5, "ribbon.middle", "ribbon", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.RibbonRightR1C6, 1, 6, "ribbon.right", "ribbon", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.FurnitureChair, 1, 13, "item.furnitureChair", "furniture", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.FurnitureBed, 1, 14, "item.furnitureBed", "furniture", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphStarEmptyR1C16, 1, 16, "glyph.star", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphStarHalfR1C17, 1, 17, "glyph.star", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphStarFullR1C18, 1, 18, "glyph.star", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphStarSparkleR1C19, 1, 19, "glyph.star", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPotionPurpleR1C20, 1, 20, "item.potion", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemCrystalBallR1C21, 1, 21, "item.crystalBall", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBenchR1C22, 1, 22, "item.bench", "furniture", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphDotBlueSmallR1C24, 1, 24, "glyph.dot", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPlusThinR1C25, 1, 25, "glyph.plus", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMinusThinR1C26, 1, 26, "glyph.minus", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowUpThinR1C27, 1, 27, "glyph.arrow", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowDownThinR1C28, 1, 28, "glyph.arrow", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMusicNoteR1C30, 1, 30, "glyph.music", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMusicOffR1C31, 1, 31, "glyph.music", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSpeakerHighR1C32, 1, 32, "glyph.speaker", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSpeakerOffR1C33, 1, 33, "glyph.speaker", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonCheckNormalR1C40, 1, 40, "button.check", "button", "confirmed", "button.check.state.r1", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonCheckHoverR1C41, 1, 41, "button.check", "button", "confirmed", "button.check.state.r1", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonCheckPressedR1C42, 1, 42, "button.check", "button", "confirmed", "button.check.state.r1", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonXMarkNormalR1C43, 1, 43, "button.xMark", "button", "confirmed", "button.xMark.state.r1", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonXMarkHoverR1C44, 1, 44, "button.xMark", "button", "confirmed", "button.xMark.state.r1", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonXMarkPressedR1C45, 1, 45, "button.xMark", "button", "confirmed", "button.xMark.state.r1", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronLeftNormalR1C46, 1, 46, "button.chevronLeft", "button", "confirmed", "button.chevronLeft.state.r1", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronLeftHoverR1C47, 1, 47, "button.chevronLeft", "button", "confirmed", "button.chevronLeft.state.r1", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronLeftPressedR1C48, 1, 48, "button.chevronLeft", "button", "confirmed", "button.chevronLeft.state.r1", "pressed"),
            EntryFor(ModernUiStyle2Icon.PanelCommonTopLeft, 2, 0, "panel.common.topLeft", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCommonTop, 2, 1, "panel.common.top", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCommonTopRight, 2, 2, "panel.common.topRight", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.RibbonShadowLeftR2C4, 2, 4, "ribbon.shadowLeft", "ribbon", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.RibbonShadowMiddleR2C5, 2, 5, "ribbon.shadowMiddle", "ribbon", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.RibbonShadowRightR2C6, 2, 6, "ribbon.shadowRight", "ribbon", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTrophySilverR2C16, 2, 16, "glyph.trophy", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTrophyGoldR2C17, 2, 17, "glyph.trophy", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMedalGoldR2C18, 2, 18, "glyph.medal", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMedalSilverR2C19, 2, 19, "glyph.medal", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPotionBlueR2C20, 2, 20, "item.potion", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemShieldBlueR2C21, 2, 21, "item.shield", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemTableR2C22, 2, 22, "item.table", "furniture", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPlantPottedR2C23, 2, 23, "item.plant", "furniture", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphQuestionMarkBlueR2C24, 2, 24, "glyph.questionMark", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphExclamationBlueR2C25, 2, 25, "glyph.exclamation", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSquareOutlineSmallR2C26, 2, 26, "glyph.square", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowLeftThinR2C27, 2, 27, "glyph.arrow", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowRightThinR2C28, 2, 28, "glyph.arrow", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMonitorScreenR2C30, 2, 30, "glyph.monitor", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphLaptopScreenR2C31, 2, 31, "glyph.laptop", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphFontLetterAR2C32, 2, 32, "glyph.font", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSortArrowsR2C33, 2, 33, "glyph.sort", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonPlusNormalR2C40, 2, 40, "button.plus", "button", "confirmed", "button.plus.state.r2", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonPlusHoverR2C41, 2, 41, "button.plus", "button", "confirmed", "button.plus.state.r2", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonPlusPressedR2C42, 2, 42, "button.plus", "button", "confirmed", "button.plus.state.r2", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMinusNormalR2C43, 2, 43, "button.minus", "button", "confirmed", "button.minus.state.r2", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMinusHoverR2C44, 2, 44, "button.minus", "button", "confirmed", "button.minus.state.r2", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMinusPressedR2C45, 2, 45, "button.minus", "button", "confirmed", "button.minus.state.r2", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronRightNormalR2C46, 2, 46, "button.chevronRight", "button", "confirmed", "button.chevronRight.state.r2", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronRightHoverR2C47, 2, 47, "button.chevronRight", "button", "confirmed", "button.chevronRight.state.r2", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronRightPressedR2C48, 2, 48, "button.chevronRight", "button", "confirmed", "button.chevronRight.state.r2", "pressed"),
            EntryFor(ModernUiStyle2Icon.PanelCommonLeft, 3, 0, "panel.common.left", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCommonFill, 3, 1, "panel.common.fill", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCommonRight, 3, 2, "panel.common.right", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.RibbonVerticalTopR3C3, 3, 3, "ribbon.verticalTop", "ribbon", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBackpackPurpleR3C16, 3, 16, "item.backpack", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBackpackTealR3C17, 3, 17, "item.backpack", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBackpackGreenR3C18, 3, 18, "item.backpack", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphClockFaceR3C20, 3, 20, "glyph.clock", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphClockHourHandR3C21, 3, 21, "glyph.clock", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonPlusNormal, 3, 40, "button.plus.normal", "button", "confirmed", "button.plus.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonPlusHover, 3, 41, "button.plus.hover", "button", "confirmed", "button.plus.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonPlusPressed, 3, 42, "button.plus.pressed", "button", "confirmed", "button.plus.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMinusNormal, 3, 43, "button.minus.normal", "button", "confirmed", "button.minus.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMinusHover, 3, 44, "button.minus.hover", "button", "confirmed", "button.minus.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMinusPressed, 3, 45, "button.minus.pressed", "button", "confirmed", "button.minus.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronUpDoubleNormalR3C46, 3, 46, "button.chevronUpDouble", "button", "confirmed", "button.chevronUpDouble.state.r3", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronUpDoubleHoverR3C47, 3, 47, "button.chevronUpDouble", "button", "confirmed", "button.chevronUpDouble.state.r3", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronUpDoublePressedR3C48, 3, 48, "button.chevronUpDouble", "button", "confirmed", "button.chevronUpDouble.state.r3", "pressed"),
            EntryFor(ModernUiStyle2Icon.PanelCommonBottomLeft, 4, 0, "panel.common.bottomLeft", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCommonBottom, 4, 1, "panel.common.bottom", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCommonBottomRight, 4, 2, "panel.common.bottomRight", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.RibbonVerticalMidR4C3, 4, 3, "ribbon.verticalMiddle", "ribbon", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBackpackNavyR4C16, 4, 16, "item.backpack", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBackpackBrownR4C17, 4, 17, "item.backpack", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBackpackRedR4C18, 4, 18, "item.backpack", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonChevronDownDoubleNormalR4C40, 4, 40, "button.chevronDownDouble", "button", "confirmed", "button.chevronDownDouble.state.r4", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronDownDoubleHoverR4C41, 4, 41, "button.chevronDownDouble", "button", "confirmed", "button.chevronDownDouble.state.r4", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronDownDoublePressedR4C42, 4, 42, "button.chevronDownDouble", "button", "confirmed", "button.chevronDownDouble.state.r4", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronLeftDoubleNormalR4C43, 4, 43, "button.chevronLeftDouble", "button", "confirmed", "button.chevronLeftDouble.state.r4", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronLeftDoubleHoverR4C44, 4, 44, "button.chevronLeftDouble", "button", "confirmed", "button.chevronLeftDouble.state.r4", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronLeftDoublePressedR4C45, 4, 45, "button.chevronLeftDouble", "button", "confirmed", "button.chevronLeftDouble.state.r4", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronRightDoubleNormalR4C46, 4, 46, "button.chevronRightDouble", "button", "confirmed", "button.chevronRightDouble.state.r4", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronRightDoubleHoverR4C47, 4, 47, "button.chevronRightDouble", "button", "confirmed", "button.chevronRightDouble.state.r4", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonChevronRightDoublePressedR4C48, 4, 48, "button.chevronRightDouble", "button", "confirmed", "button.chevronRightDouble.state.r4", "pressed"),
            EntryFor(ModernUiStyle2Icon.PanelBaseSquareSmallR5C0, 5, 0, "panel.baseSquareSmall", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.RibbonVerticalBotR5C3, 5, 3, "ribbon.verticalBottom", "ribbon", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPhoneGreenR5C16, 5, 16, "item.phoneGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonTrophyNormalR5C40, 5, 40, "button.trophy", "button", "confirmed", "button.trophy.state.r5", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonTrophyHoverR5C41, 5, 41, "button.trophy", "button", "confirmed", "button.trophy.state.r5", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonTrophyPressedR5C42, 5, 42, "button.trophy", "button", "confirmed", "button.trophy.state.r5", "pressed"),
            EntryFor(ModernUiStyle2Icon.SlotBaseR6C0, 6, 0, "slot.base", "slot", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPhoneRedR6C16, 6, 16, "item.phoneRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemEnvelopeGreenR6C17, 6, 17, "item.envelopeGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemEnvelopeRedR6C18, 6, 18, "item.envelopeRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPotionRedR6C20, 6, 20, "item.potionRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPotionYellowR6C21, 6, 21, "item.potionYellow", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.FurnitureBedR6C22, 6, 22, "furniture.bed", "furniture", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.FurnitureChestR6C23, 6, 23, "furniture.chest", "furniture", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonStarNormalR6C40, 6, 40, "button.star", "button", "confirmed", "button.star.state.r6", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonStarHoverR6C41, 6, 41, "button.star", "button", "confirmed", "button.star.state.r6", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonStarPressedR6C42, 6, 42, "button.star", "button", "confirmed", "button.star.state.r6", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonHeartNormalR6C43, 6, 43, "button.heart", "button", "confirmed", "button.heart.state.r6", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonHeartHoverR6C44, 6, 44, "button.heart", "button", "confirmed", "button.heart.state.r6", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonHeartPressedR6C45, 6, 45, "button.heart", "button", "confirmed", "button.heart.state.r6", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonSettingsNormalR6C46, 6, 46, "button.settings", "button", "confirmed", "button.settings.state.r6", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonSettingsHoverR6C47, 6, 47, "button.settings", "button", "confirmed", "button.settings.state.r6", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonSettingsPressedR6C48, 6, 48, "button.settings", "button", "confirmed", "button.settings.state.r6", "pressed"),
            EntryFor(ModernUiStyle2Icon.SlotHighlightR7C0, 7, 0, "slot.highlight", "slot", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBookGreenR7C16, 7, 16, "item.bookGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBookRedR7C17, 7, 17, "item.bookRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBookBlueR7C18, 7, 18, "item.bookBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemSwordGreenR7C20, 7, 20, "item.swordGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemSwordRedR7C21, 7, 21, "item.swordRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemSwordBlueR7C22, 7, 22, "item.swordBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonPlayNormalR7C40, 7, 40, "button.play", "button", "confirmed", "button.play.state.r7", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonPlayHoverR7C41, 7, 41, "button.play", "button", "confirmed", "button.play.state.r7", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonPlayPressedR7C42, 7, 42, "button.play", "button", "confirmed", "button.play.state.r7", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonPauseNormalR7C43, 7, 43, "button.pause", "button", "confirmed", "button.pause.state.r7", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonPauseHoverR7C44, 7, 44, "button.pause", "button", "confirmed", "button.pause.state.r7", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonPausePressedR7C45, 7, 45, "button.pause", "button", "confirmed", "button.pause.state.r7", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonStopNormalR7C46, 7, 46, "button.stop", "button", "confirmed", "button.stop.state.r7", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonStopHoverR7C47, 7, 47, "button.stop", "button", "confirmed", "button.stop.state.r7", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonStopPressedR7C48, 7, 48, "button.stop", "button", "confirmed", "button.stop.state.r7", "pressed"),
            EntryFor(ModernUiStyle2Icon.ItemAxeGreenR8C16, 8, 16, "item.axeGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemAxeRedR8C17, 8, 17, "item.axeRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemAxeBlueR8C18, 8, 18, "item.axeBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPickaxeGreenR8C20, 8, 20, "item.pickaxeGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPickaxeRedR8C21, 8, 21, "item.pickaxeRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPickaxeBlueR8C22, 8, 22, "item.pickaxeBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonFastForwardNormalR8C40, 8, 40, "button.fastForward", "button", "confirmed", "button.fastForward.state.r8", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonFastForwardHoverR8C41, 8, 41, "button.fastForward", "button", "confirmed", "button.fastForward.state.r8", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonFastForwardPressedR8C42, 8, 42, "button.fastForward", "button", "confirmed", "button.fastForward.state.r8", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonFastBackwardNormalR8C43, 8, 43, "button.fastBackward", "button", "confirmed", "button.fastBackward.state.r8", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonFastBackwardHoverR8C44, 8, 44, "button.fastBackward", "button", "confirmed", "button.fastBackward.state.r8", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonFastBackwardPressedR8C45, 8, 45, "button.fastBackward", "button", "confirmed", "button.fastBackward.state.r8", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonAudioNormalR8C46, 8, 46, "button.audio", "button", "confirmed", "button.audio.state.r8", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonAudioHoverR8C47, 8, 47, "button.audio", "button", "confirmed", "button.audio.state.r8", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonAudioPressedR8C48, 8, 48, "button.audio", "button", "confirmed", "button.audio.state.r8", "pressed"),
            EntryFor(ModernUiStyle2Icon.ItemHammerGreenR9C16, 9, 16, "item.hammerGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemHammerRedR9C17, 9, 17, "item.hammerRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemHammerBlueR9C18, 9, 18, "item.hammerBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemShovelGreenR9C20, 9, 20, "item.shovelGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemShovelRedR9C21, 9, 21, "item.shovelRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemShovelBlueR9C22, 9, 22, "item.shovelBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonHomeNormalR9C40, 9, 40, "button.home", "button", "confirmed", "button.home.state.r9", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonHomeHoverR9C41, 9, 41, "button.home", "button", "confirmed", "button.home.state.r9", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonHomePressedR9C42, 9, 42, "button.home", "button", "confirmed", "button.home.state.r9", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonInfoNormalR9C43, 9, 43, "button.info", "button", "confirmed", "button.info.state.r9", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonInfoHoverR9C44, 9, 44, "button.info", "button", "confirmed", "button.info.state.r9", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonInfoPressedR9C45, 9, 45, "button.info", "button", "confirmed", "button.info.state.r9", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonHelpNormalR9C46, 9, 46, "button.help", "button", "confirmed", "button.help.state.r9", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonHelpHoverR9C47, 9, 47, "button.help", "button", "confirmed", "button.help.state.r9", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonHelpPressedR9C48, 9, 48, "button.help", "button", "confirmed", "button.help.state.r9", "pressed"),
            EntryFor(ModernUiStyle2Icon.ItemFishingRodGreenR10C16, 10, 16, "item.fishingRodGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemFishingRodRedR10C17, 10, 17, "item.fishingRodRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemFishingRodBlueR10C18, 10, 18, "item.fishingRodBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBowGreenR10C20, 10, 20, "item.bowGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBowRedR10C21, 10, 21, "item.bowRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBowBlueR10C22, 10, 22, "item.bowBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonMailNormalR10C40, 10, 40, "button.mail", "button", "confirmed", "button.mail.state.r10", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMailHoverR10C41, 10, 41, "button.mail", "button", "confirmed", "button.mail.state.r10", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMailPressedR10C42, 10, 42, "button.mail", "button", "confirmed", "button.mail.state.r10", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonChatNormalR10C43, 10, 43, "button.chat", "button", "confirmed", "button.chat.state.r10", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonChatHoverR10C44, 10, 44, "button.chat", "button", "confirmed", "button.chat.state.r10", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonChatPressedR10C45, 10, 45, "button.chat", "button", "confirmed", "button.chat.state.r10", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonProfileNormalR10C46, 10, 46, "button.profile", "button", "confirmed", "button.profile.state.r10", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonProfileHoverR10C47, 10, 47, "button.profile", "button", "confirmed", "button.profile.state.r10", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonProfilePressedR10C48, 10, 48, "button.profile", "button", "confirmed", "button.profile.state.r10", "pressed"),
            EntryFor(ModernUiStyle2Icon.PanelThinCornerTopLeftR11C0, 11, 0, "panel.thinCornerTopLeft", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelThinEdgeTopR11C1, 11, 1, "panel.thinEdgeTop", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelThinCornerTopRightR11C2, 11, 2, "panel.thinCornerTopRight", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemArrowGreenR11C16, 11, 16, "item.arrowGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemArrowRedR11C17, 11, 17, "item.arrowRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemArrowBlueR11C18, 11, 18, "item.arrowBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemShieldGreenR11C20, 11, 20, "item.shieldGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemShieldRedR11C21, 11, 21, "item.shieldRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemShieldBlueR11C22, 11, 22, "item.shieldBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonCapsuleLeftR11C34, 11, 34, "button.capsuleLeft", "button", "confirmed", "button.capsule.state.r11", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonCapsuleMiddleR11C35, 11, 35, "button.capsuleMiddle", "button", "confirmed", "button.capsule.state.r11", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonCapsuleRightR11C36, 11, 36, "button.capsuleRight", "button", "confirmed", "button.capsule.state.r11", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonRefreshNormalR11C40, 11, 40, "button.refresh", "button", "confirmed", "button.refresh.state.r11", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonRefreshHoverR11C41, 11, 41, "button.refresh", "button", "confirmed", "button.refresh.state.r11", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonRefreshPressedR11C42, 11, 42, "button.refresh", "button", "confirmed", "button.refresh.state.r11", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonLoginNormalR11C43, 11, 43, "button.login", "button", "confirmed", "button.login.state.r11", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonLoginHoverR11C44, 11, 44, "button.login", "button", "confirmed", "button.login.state.r11", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonLoginPressedR11C45, 11, 45, "button.login", "button", "confirmed", "button.login.state.r11", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonLogoutNormalR11C46, 11, 46, "button.logout", "button", "confirmed", "button.logout.state.r11", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonLogoutHoverR11C47, 11, 47, "button.logout", "button", "confirmed", "button.logout.state.r11", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonLogoutPressedR11C48, 11, 48, "button.logout", "button", "confirmed", "button.logout.state.r11", "pressed"),
            EntryFor(ModernUiStyle2Icon.PanelThinEdgeLeftR12C0, 12, 0, "panel.thinEdgeLeft", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemKeyGreenR12C16, 12, 16, "item.keyGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemKeyRedR12C17, 12, 17, "item.keyRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemKeyBlueR12C18, 12, 18, "item.keyBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemCoinGreenR12C20, 12, 20, "item.coinGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemCoinRedR12C21, 12, 21, "item.coinRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemCoinBlueR12C22, 12, 22, "item.coinBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonZoomInNormalR12C40, 12, 40, "button.zoomIn", "button", "confirmed", "button.zoomIn.state.r12", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonZoomInHoverR12C41, 12, 41, "button.zoomIn", "button", "confirmed", "button.zoomIn.state.r12", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonZoomInPressedR12C42, 12, 42, "button.zoomIn", "button", "confirmed", "button.zoomIn.state.r12", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonZoomOutNormalR12C43, 12, 43, "button.zoomOut", "button", "confirmed", "button.zoomOut.state.r12", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonZoomOutHoverR12C44, 12, 44, "button.zoomOut", "button", "confirmed", "button.zoomOut.state.r12", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonZoomOutPressedR12C45, 12, 45, "button.zoomOut", "button", "confirmed", "button.zoomOut.state.r12", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonSearchNormalR12C46, 12, 46, "button.search", "button", "confirmed", "button.search.state.r12", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonSearchHoverR12C47, 12, 47, "button.search", "button", "confirmed", "button.search.state.r12", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonSearchPressedR12C48, 12, 48, "button.search", "button", "confirmed", "button.search.state.r12", "pressed"),
            EntryFor(ModernUiStyle2Icon.PanelThinCornerBottomLeftR13C0, 13, 0, "panel.thinCornerBottomLeft", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemScrollGreenR13C16, 13, 16, "item.scrollGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemScrollRedR13C17, 13, 17, "item.scrollRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemScrollBlueR13C18, 13, 18, "item.scrollBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemMapGreenR13C20, 13, 20, "item.mapGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemMapRedR13C21, 13, 21, "item.mapRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemMapBlueR13C22, 13, 22, "item.mapBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonEditNormalR13C40, 13, 40, "button.edit", "button", "confirmed", "button.edit.state.r13", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonEditHoverR13C41, 13, 41, "button.edit", "button", "confirmed", "button.edit.state.r13", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonEditPressedR13C42, 13, 42, "button.edit", "button", "confirmed", "button.edit.state.r13", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonSaveNormalR13C43, 13, 43, "button.save", "button", "confirmed", "button.save.state.r13", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonSaveHoverR13C44, 13, 44, "button.save", "button", "confirmed", "button.save.state.r13", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonSavePressedR13C45, 13, 45, "button.save", "button", "confirmed", "button.save.state.r13", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonDeleteNormalR13C46, 13, 46, "button.delete", "button", "confirmed", "button.delete.state.r13", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonDeleteHoverR13C47, 13, 47, "button.delete", "button", "confirmed", "button.delete.state.r13", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonDeletePressedR13C48, 13, 48, "button.delete", "button", "confirmed", "button.delete.state.r13", "pressed"),
            EntryFor(ModernUiStyle2Icon.ItemGemGreenR14C16, 14, 16, "item.gemGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemGemRedR14C17, 14, 17, "item.gemRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemGemBlueR14C18, 14, 18, "item.gemBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemRingGreenR14C20, 14, 20, "item.ringGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemRingRedR14C21, 14, 21, "item.ringRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemRingBlueR14C22, 14, 22, "item.ringBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonTrophySmallNormalR14C40, 14, 40, "button.trophySmall", "button", "confirmed", "button.trophySmall.state.r14", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonTrophySmallHoverR14C41, 14, 41, "button.trophySmall", "button", "confirmed", "button.trophySmall.state.r14", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonTrophySmallPressedR14C42, 14, 42, "button.trophySmall", "button", "confirmed", "button.trophySmall.state.r14", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMedalSmallNormalR14C43, 14, 43, "button.medalSmall", "button", "confirmed", "button.medalSmall.state.r14", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMedalSmallHoverR14C44, 14, 44, "button.medalSmall", "button", "confirmed", "button.medalSmall.state.r14", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMedalSmallPressedR14C45, 14, 45, "button.medalSmall", "button", "confirmed", "button.medalSmall.state.r14", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonGiftSmallNormalR14C46, 14, 46, "button.giftSmall", "button", "confirmed", "button.giftSmall.state.r14", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonGiftSmallHoverR14C47, 14, 47, "button.giftSmall", "button", "confirmed", "button.giftSmall.state.r14", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonGiftSmallPressedR14C48, 14, 48, "button.giftSmall", "button", "confirmed", "button.giftSmall.state.r14", "pressed"),
            EntryFor(ModernUiStyle2Icon.CursorPointerDefaultR15C14, 15, 14, "cursor.pointer", "cursor", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemMeatGreenR15C16, 15, 16, "item.meatGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemMeatRedR15C17, 15, 17, "item.meatRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemMeatBlueR15C18, 15, 18, "item.meatBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBreadGreenR15C20, 15, 20, "item.breadGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBreadRedR15C21, 15, 21, "item.breadRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBreadBlueR15C22, 15, 22, "item.breadBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.DirectionUpR15C24, 15, 24, "direction.up", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.DirectionDownR15C25, 15, 25, "direction.down", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.DirectionLeftR15C26, 15, 26, "direction.left", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.DirectionRightR15C27, 15, 27, "direction.right", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonArrowUpNormalR15C40, 15, 40, "button.arrowUp", "button", "confirmed", "button.arrowUp.state.r15", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowUpHoverR15C41, 15, 41, "button.arrowUp", "button", "confirmed", "button.arrowUp.state.r15", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowUpPressedR15C42, 15, 42, "button.arrowUp", "button", "confirmed", "button.arrowUp.state.r15", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowDownNormalR15C43, 15, 43, "button.arrowDown", "button", "confirmed", "button.arrowDown.state.r15", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowDownHoverR15C44, 15, 44, "button.arrowDown", "button", "confirmed", "button.arrowDown.state.r15", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowDownPressedR15C45, 15, 45, "button.arrowDown", "button", "confirmed", "button.arrowDown.state.r15", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowLeftNormalR15C46, 15, 46, "button.arrowLeft", "button", "confirmed", "button.arrowLeft.state.r15", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowLeftHoverR15C47, 15, 47, "button.arrowLeft", "button", "confirmed", "button.arrowLeft.state.r15", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowLeftPressedR15C48, 15, 48, "button.arrowLeft", "button", "confirmed", "button.arrowLeft.state.r15", "pressed"),
            EntryFor(ModernUiStyle2Icon.ItemAppleGreenR16C16, 16, 16, "item.appleGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemAppleRedR16C17, 16, 17, "item.appleRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemAppleBlueR16C18, 16, 18, "item.appleBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemCrystalGreenR16C20, 16, 20, "item.crystalGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemCrystalRedR16C21, 16, 21, "item.crystalRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemCrystalBlueR16C22, 16, 22, "item.crystalBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPlayR16C24, 16, 24, "glyph.play", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPauseR16C25, 16, 25, "glyph.pause", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphStopR16C26, 16, 26, "glyph.stop", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphFastBackwardR16C27, 16, 27, "glyph.fastBackward", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphFastForwardR16C28, 16, 28, "glyph.fastForward", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonSoundOnR16C40, 16, 40, "button.soundOn", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonSoundOffR16C43, 16, 43, "button.soundOff", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonMusicToggleR16C46, 16, 46, "button.music", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemFishGreenR17C16, 17, 16, "item.fishGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemFishBlueR17C18, 17, 18, "item.fishBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemMeatLegGreenR17C21, 17, 21, "item.meatGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemMeatLegBlueR17C22, 17, 22, "item.meatBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCirclePlayR17C24, 17, 24, "glyph.circlePlay", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCirclePauseR17C25, 17, 25, "glyph.circlePause", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCircleStopR17C26, 17, 26, "glyph.circleStop", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonStarNormalR17C40, 17, 40, "button.star", "button", "confirmed", "button.star.state.r17", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonStarHoverR17C41, 17, 41, "button.star", "button", "confirmed", "button.star.state.r17", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonStarPressedR17C42, 17, 42, "button.star", "button", "confirmed", "button.star.state.r17", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonHeartNormalR17C43, 17, 43, "button.heart", "button", "confirmed", "button.heart.state.r17", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonHeartHoverR17C44, 17, 44, "button.heart", "button", "confirmed", "button.heart.state.r17", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonHeartPressedR17C45, 17, 45, "button.heart", "button", "confirmed", "button.heart.state.r17", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonGearNormalR17C46, 17, 46, "button.gear", "button", "confirmed", "button.gear.state.r17", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonGearHoverR17C47, 17, 47, "button.gear", "button", "confirmed", "button.gear.state.r17", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonGearPressedR17C48, 17, 48, "button.gear", "button", "confirmed", "button.gear.state.r17", "pressed"),
            EntryFor(ModernUiStyle2Icon.ItemFlaskGreenR18C16, 18, 16, "item.flaskGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemFlaskBlueR18C18, 18, 18, "item.flaskBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMailOpenR18C24, 18, 24, "glyph.mailOpen", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMailClosedR18C25, 18, 25, "glyph.mailClosed", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBerriesGreenR19C16, 19, 16, "item.berriesGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBerriesBlueR19C18, 19, 18, "item.berriesBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemCarrotGreenR19C21, 19, 21, "item.carrotGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemCarrotBlueR19C22, 19, 22, "item.carrotBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemMushroomGreenR20C16, 20, 16, "item.mushroomGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemMushroomBlueR20C18, 20, 18, "item.mushroomBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTrophyR20C24, 20, 24, "glyph.trophy", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelThinEdgeLeftR21C0, 21, 0, "panel.thinEdgeLeft", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemLeafGreenR21C16, 21, 16, "item.leafGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemLeafBlueR21C18, 21, 18, "item.leafBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemEggGreenR21C21, 21, 21, "item.eggGreen", "item", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ItemEggBlueR21C22, 21, 22, "item.eggBlue", "item", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSpeakerMuteR21C24, 21, 24, "glyph.speakerMute", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSpeakerLowR21C25, 21, 25, "glyph.speakerLow", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSpeakerHighR21C26, 21, 26, "glyph.speakerHigh", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPouchGreenR22C15, 22, 15, "item.pouchGreen", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPouchRedR22C16, 22, 16, "item.pouchRed", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPouchBlueR22C17, 22, 17, "item.pouchBlue", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemPouchYellowR22C18, 22, 18, "item.pouchYellow", "item", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.StatusHeartSmallR22C24, 22, 24, "status.heartSmall", "status", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.StatusStarSmallR22C25, 22, 25, "status.starSmall", "status", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.StatusShieldSmallR22C26, 22, 26, "status.shieldSmall", "status", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.StatusSwordSmallR22C27, 22, 27, "status.swordSmall", "status", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.DirectionSharpUpR23C24, 23, 24, "direction.sharpUp", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.DirectionSharpDownR23C25, 23, 25, "direction.sharpDown", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.DirectionSharpLeftR23C26, 23, 26, "direction.sharpLeft", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.DirectionSharpRightR23C27, 23, 27, "direction.sharpRight", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ToggleCheckboxOffR24C24, 24, 24, "toggle.checkboxOff", "toggle", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ToggleCheckboxOnR24C25, 24, 25, "toggle.checkboxOn", "toggle", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ToggleRadioOffR24C26, 24, 26, "toggle.radioOff", "toggle", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ToggleRadioOnR24C27, 24, 27, "toggle.radioOn", "toggle", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.StatusGaugeStartR25C32, 25, 32, "status.gaugeStart", "status", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.StatusGaugeMiddleR25C33, 25, 33, "status.gaugeMiddle", "status", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.StatusGaugeEndR25C34, 25, 34, "status.gaugeEnd", "status", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonExitNormalR25C40, 25, 40, "button.exit", "button", "confirmed", "button.exit.state.r25", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonExitHoverR25C41, 25, 41, "button.exit", "button", "confirmed", "button.exit.state.r25", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonExitPressedR25C42, 25, 42, "button.exit", "button", "confirmed", "button.exit.state.r25", "pressed"),
            EntryFor(ModernUiStyle2Icon.SlotBaseGreenR26C16, 26, 16, "slot.baseGreen", "slot", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.SlotBaseRedR26C17, 26, 17, "slot.baseRed", "slot", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.SlotBaseBlueR26C18, 26, 18, "slot.baseBlue", "slot", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSearchSmallR26C24, 26, 24, "glyph.searchSmall", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphEditSmallR26C25, 26, 25, "glyph.editSmall", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSaveSmallR26C26, 26, 26, "glyph.saveSmall", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixCheckNormalR26C40, 26, 40, "buttonMatrix.check", "buttonMatrix", "confirmed", "buttonMatrix.check.state.r26", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixCheckHoverR26C41, 26, 41, "buttonMatrix.check", "buttonMatrix", "confirmed", "buttonMatrix.check.state.r26", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixCheckPressedR26C42, 26, 42, "buttonMatrix.check", "buttonMatrix", "confirmed", "buttonMatrix.check.state.r26", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixXMarkNormalR26C43, 26, 43, "buttonMatrix.xMark", "buttonMatrix", "confirmed", "buttonMatrix.xMark.state.r26", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixXMarkHoverR26C44, 26, 44, "buttonMatrix.xMark", "buttonMatrix", "confirmed", "buttonMatrix.xMark.state.r26", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixXMarkPressedR26C45, 26, 45, "buttonMatrix.xMark", "buttonMatrix", "confirmed", "buttonMatrix.xMark.state.r26", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlusNormalR26C46, 26, 46, "buttonMatrix.plus", "buttonMatrix", "confirmed", "buttonMatrix.plus.state.r26", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlusHoverR26C47, 26, 47, "buttonMatrix.plus", "buttonMatrix", "confirmed", "buttonMatrix.plus.state.r26", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlusPressedR26C48, 26, 48, "buttonMatrix.plus", "buttonMatrix", "confirmed", "buttonMatrix.plus.state.r26", "pressed"),
            EntryFor(ModernUiStyle2Icon.SlotBaseDarkGreenR27C16, 27, 16, "slot.baseDarkGreen", "slot", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphDeleteSmallR27C24, 27, 24, "glyph.deleteSmall", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphLockSmallR27C25, 27, 25, "glyph.lockSmall", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixMinusNormalR27C40, 27, 40, "buttonMatrix.minus", "buttonMatrix", "confirmed", "buttonMatrix.minus.state.r27", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixMinusHoverR27C41, 27, 41, "buttonMatrix.minus", "buttonMatrix", "confirmed", "buttonMatrix.minus.state.r27", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixMinusPressedR27C42, 27, 42, "buttonMatrix.minus", "buttonMatrix", "confirmed", "buttonMatrix.minus.state.r27", "pressed"),
            EntryFor(ModernUiStyle2Icon.GlyphChevronUpSmallR28C24, 28, 24, "glyph.chevronUpSmall", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphChevronDownSmallR28C25, 28, 25, "glyph.chevronDownSmall", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowUpNormalR28C40, 28, 40, "buttonMatrix.arrowUp", "buttonMatrix", "confirmed", "buttonMatrix.arrowUp.state.r28", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowUpHoverR28C41, 28, 41, "buttonMatrix.arrowUp", "buttonMatrix", "confirmed", "buttonMatrix.arrowUp.state.r28", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowUpPressedR28C42, 28, 42, "buttonMatrix.arrowUp", "buttonMatrix", "confirmed", "buttonMatrix.arrowUp.state.r28", "pressed"),
            EntryFor(ModernUiStyle2Icon.GlyphChevronLeftSmallR29C24, 29, 24, "glyph.chevronLeftSmall", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphChevronRightSmallR29C25, 29, 25, "glyph.chevronRightSmall", "glyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowDownNormalR29C40, 29, 40, "buttonMatrix.arrowDown", "buttonMatrix", "confirmed", "buttonMatrix.arrowDown.state.r29", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowDownHoverR29C41, 29, 41, "buttonMatrix.arrowDown", "buttonMatrix", "confirmed", "buttonMatrix.arrowDown.state.r29", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowDownPressedR29C42, 29, 42, "buttonMatrix.arrowDown", "buttonMatrix", "confirmed", "buttonMatrix.arrowDown.state.r29", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowLeftNormalR30C40, 30, 40, "buttonMatrix.arrowLeft", "buttonMatrix", "confirmed", "buttonMatrix.arrowLeft.state.r30", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowLeftHoverR30C41, 30, 41, "buttonMatrix.arrowLeft", "buttonMatrix", "confirmed", "buttonMatrix.arrowLeft.state.r30", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowLeftPressedR30C42, 30, 42, "buttonMatrix.arrowLeft", "buttonMatrix", "confirmed", "buttonMatrix.arrowLeft.state.r30", "pressed"),
            EntryFor(ModernUiStyle2Icon.PanelCornerBottomLeftR31C0, 31, 0, "panel.cornerBottomLeft", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelEdgeBottomR31C1, 31, 1, "panel.edgeBottom", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCornerBottomRightR31C2, 31, 2, "panel.cornerBottomRight", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowRightNormalR31C40, 31, 40, "buttonMatrix.arrowRight", "buttonMatrix", "confirmed", "buttonMatrix.arrowRight.state.r31", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowRightHoverR31C41, 31, 41, "buttonMatrix.arrowRight", "buttonMatrix", "confirmed", "buttonMatrix.arrowRight.state.r31", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowRightPressedR31C42, 31, 42, "buttonMatrix.arrowRight", "buttonMatrix", "confirmed", "buttonMatrix.arrowRight.state.r31", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlayNormalR31C43, 31, 43, "buttonMatrix.play", "buttonMatrix", "confirmed", "buttonMatrix.play.state.r31", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlayHoverR31C44, 31, 44, "buttonMatrix.play", "buttonMatrix", "confirmed", "buttonMatrix.play.state.r31", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlayPressedR31C45, 31, 45, "buttonMatrix.play", "buttonMatrix", "confirmed", "buttonMatrix.play.state.r31", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPauseNormalR32C40, 32, 40, "buttonMatrix.pause", "buttonMatrix", "confirmed", "buttonMatrix.pause.state.r32", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPauseHoverR32C41, 32, 41, "buttonMatrix.pause", "buttonMatrix", "confirmed", "buttonMatrix.pause.state.r32", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPausePressedR32C42, 32, 42, "buttonMatrix.pause", "buttonMatrix", "confirmed", "buttonMatrix.pause.state.r32", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixStopNormalR32C43, 32, 43, "buttonMatrix.stop", "buttonMatrix", "confirmed", "buttonMatrix.stop.state.r32", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixStopHoverR32C44, 32, 44, "buttonMatrix.stop", "buttonMatrix", "confirmed", "buttonMatrix.stop.state.r32", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixStopPressedR32C45, 32, 45, "buttonMatrix.stop", "buttonMatrix", "confirmed", "buttonMatrix.stop.state.r32", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixHomeNormalR33C40, 33, 40, "buttonMatrix.home", "buttonMatrix", "confirmed", "buttonMatrix.home.state.r33", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixHomeHoverR33C41, 33, 41, "buttonMatrix.home", "buttonMatrix", "confirmed", "buttonMatrix.home.state.r33", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixHomePressedR33C42, 33, 42, "buttonMatrix.home", "buttonMatrix", "confirmed", "buttonMatrix.home.state.r33", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixDeleteNormalR33C46, 33, 46, "buttonMatrix.delete", "buttonMatrix", "confirmed", "buttonMatrix.delete.state.r33", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixDeleteHoverR33C47, 33, 47, "buttonMatrix.delete", "buttonMatrix", "confirmed", "buttonMatrix.delete.state.r33", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixDeletePressedR33C48, 33, 48, "buttonMatrix.delete", "buttonMatrix", "confirmed", "buttonMatrix.delete.state.r33", "pressed"),
        };

        public static ModernUiSpriteKey GetSpriteKey(ModernUiStyle2Icon icon)
        {
            foreach (Entry entry in Entries)
            {
                if (entry.Icon == icon)
                {
                    return entry.SpriteKey;
                }
            }

            throw new ArgumentOutOfRangeException(nameof(icon), icon, "Unknown Modern UI Style2 icon.");
        }

        private static Entry EntryFor(ModernUiStyle2Icon icon, int row, int column, string semanticId, string category, string confidence, string stateGroupId, string stateRole)
        {
            string coord = "r" + row + "_c" + column;
            string sprite = Prefix + coord;
            return new Entry(icon, row, column, coord, sprite, semanticId, category, stateGroupId, stateRole, confidence);
        }

        public readonly struct Entry
        {
            public Entry(ModernUiStyle2Icon icon, int row, int column, string coordinate, string spriteName, string semanticId, string category, string stateGroupId, string stateRole, string confidence)
            {
                Icon = icon;
                Row = row;
                Column = column;
                Coordinate = coordinate;
                SpriteName = spriteName;
                SemanticId = semanticId;
                Category = category;
                StateGroupId = stateGroupId;
                StateRole = stateRole;
                Confidence = confidence;
                SpriteKey = new ModernUiSpriteKey(ModernUiStyle2Sprites.SheetAddress, spriteName, row, column, semanticId);
            }

            public ModernUiStyle2Icon Icon { get; }
            public int Row { get; }
            public int Column { get; }
            public string Coordinate { get; }
            public string SpriteName { get; }
            public string SemanticId { get; }
            public string Category { get; }
            public string StateGroupId { get; }
            public string StateRole { get; }
            public string Confidence { get; }
            public ModernUiSpriteKey SpriteKey { get; }
        }
    }
}
