using System;
using System.Collections.Generic;

namespace Rootborn.Game.Common
{
    public static class ModernUiStyle2IconCatalog
    {
        private const string Prefix = "ModernUI_16_Style2_";

        public static readonly IReadOnlyList<Entry> Entries = new[]
        {
            EntryFor(ModernUiStyle2Icon.PanelBase, 0, 0, "panel.base", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.RibbonItems, 0, 1, "ribbon.items", "ribbon", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.RibbonDescription, 0, 2, "ribbon.description", "ribbon", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.RibbonEquipment, 0, 3, "ribbon.equipment", "ribbon", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.SlotItem, 0, 4, "slot.item", "slot", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.SlotEquipment, 0, 5, "slot.equipment", "slot", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonSmall, 0, 8, "button.small", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemGiftGreen, 0, 9, "item.giftGreen", "itemIcon", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ItemGiftRed, 0, 10, "item.giftRed", "itemIcon", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBadgeBlue, 0, 11, "item.badgeBlue", "itemIcon", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ItemMedal, 0, 12, "item.medal", "itemIcon", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ItemCardboardBox, 0, 13, "item.cardboardBox", "itemIcon", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ItemMailPackage, 0, 14, "item.mailPackage", "itemIcon", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.PortraitCharacter, 1, 0, "portrait.character", "portrait", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelFill, 1, 1, "panel.fill", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelInsetFill, 1, 2, "panel.insetFill", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonAction, 1, 8, "button.action", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonClose, 1, 9, "button.close", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ItemLightning, 1, 10, "item.lightning", "itemIcon", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ItemStarFilled, 1, 11, "item.starFilled", "itemIcon", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ItemStarOutline, 1, 12, "item.starOutline", "itemIcon", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.FurnitureChair, 1, 13, "furniture.chair", "furniture", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.FurnitureBed, 1, 14, "furniture.bed", "furniture", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphLock, 1, 24, "glyph.lock", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphLockOpen, 1, 25, "glyph.lockOpen", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphGrid, 1, 26, "glyph.grid", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphBack, 1, 27, "glyph.back", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTree, 1, 28, "glyph.tree", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphDiamond, 1, 29, "glyph.diamond", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphHome, 1, 30, "glyph.home", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphList, 1, 31, "glyph.list", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTrash, 1, 32, "glyph.trash", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonLockNormal, 1, 34, "button.lock.normal", "button", "confirmed", "button.lock.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonLockHover, 1, 35, "button.lock.hover", "button", "confirmed", "button.lock.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonLockPressed, 1, 36, "button.lock.pressed", "button", "confirmed", "button.lock.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonGridNormal, 1, 37, "button.grid.normal", "button", "confirmed", "button.grid.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonGridHover, 1, 38, "button.grid.hover", "button", "confirmed", "button.grid.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonGridPressed, 1, 39, "button.grid.pressed", "button", "confirmed", "button.grid.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonBackNormal, 1, 40, "button.back.normal", "button", "confirmed", "button.back.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonBackHover, 1, 41, "button.back.hover", "button", "confirmed", "button.back.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonBackPressed, 1, 42, "button.back.pressed", "button", "confirmed", "button.back.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonSlidersNormal, 1, 43, "button.sliders.normal", "button", "confirmed", "button.sliders.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonSlidersHover, 1, 44, "button.sliders.hover", "button", "confirmed", "button.sliders.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonSlidersPressed, 1, 45, "button.sliders.pressed", "button", "confirmed", "button.sliders.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.PanelCommonTopLeft, 2, 0, "panel.common.topLeft", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCommonTop, 2, 1, "panel.common.top", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCommonTopRight, 2, 2, "panel.common.topRight", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ScrollbarThumb, 2, 3, "scrollbar.thumb", "scrollbar", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.TabTitle, 2, 8, "tab.title", "tab", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.TabSelected, 2, 9, "tab.selected", "tab", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCheck, 2, 24, "glyph.check", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCross, 2, 25, "glyph.cross", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPlus, 2, 26, "glyph.plus", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMinus, 2, 27, "glyph.minus", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowRight, 2, 28, "glyph.arrowRight", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowLeft, 2, 29, "glyph.arrowLeft", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowDown, 2, 30, "glyph.arrowDown", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowUp, 2, 31, "glyph.arrowUp", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphListAdd, 2, 32, "glyph.listAdd", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCommonLeft, 3, 0, "panel.common.left", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCommonFill, 3, 1, "panel.common.fill", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.PanelCommonRight, 3, 2, "panel.common.right", "panel", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ScrollbarTrack, 3, 3, "scrollbar.track", "scrollbar", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.TabMisc, 3, 9, "tab.misc", "tab", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphRefresh, 3, 24, "glyph.refresh", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowsVertical, 3, 25, "glyph.arrowsVertical", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPlay, 3, 26, "glyph.play", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMail, 3, 27, "glyph.mail", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPlaySmall, 3, 28, "glyph.playSmall", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPreviousSmall, 3, 29, "glyph.previousSmall", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTriangleDown, 3, 30, "glyph.triangleDown", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTriangleUp, 3, 31, "glyph.triangleUp", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphFilter, 3, 32, "glyph.filter", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonCheckNormal, 3, 34, "button.check.normal", "button", "confirmed", "button.check.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonCheckHover, 3, 35, "button.check.hover", "button", "confirmed", "button.check.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonCheckPressed, 3, 36, "button.check.pressed", "button", "confirmed", "button.check.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonCrossNormal, 3, 37, "button.cross.normal", "button", "confirmed", "button.cross.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonCrossHover, 3, 38, "button.cross.hover", "button", "confirmed", "button.cross.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonCrossPressed, 3, 39, "button.cross.pressed", "button", "confirmed", "button.cross.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonPlusNormal, 3, 40, "button.plus.normal", "button", "confirmed", "button.plus.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonPlusHover, 3, 41, "button.plus.hover", "button", "confirmed", "button.plus.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonIconHeightFrame0, 3, 42, "button.icon.heightFrame0", "button", "confirmed", "button.icon.heightFrame", "frame0"),
            EntryFor(ModernUiStyle2Icon.ButtonIconHeightFrame1, 3, 43, "button.icon.heightFrame1", "button", "confirmed", "button.icon.heightFrame", "frame1"),
            EntryFor(ModernUiStyle2Icon.ButtonIconHeightFrame2, 3, 44, "button.icon.heightFrame2", "button", "confirmed", "button.icon.heightFrame", "frame2"),
            EntryFor(ModernUiStyle2Icon.ButtonMinusPressed, 3, 45, "button.minus.pressed", "button", "confirmed", "button.minus.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonListAddNormal, 3, 46, "button.listAdd.normal", "button", "confirmed", "button.listAdd.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonListAddHover, 3, 47, "button.listAdd.hover", "button", "confirmed", "button.listAdd.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonListAddPressed, 3, 48, "button.listAdd.pressed", "button", "confirmed", "button.listAdd.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.GlyphUser, 4, 24, "glyph.user", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphQuestion, 4, 25, "glyph.question", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTrophy, 4, 26, "glyph.trophy", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphClock, 4, 27, "glyph.clock", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPause, 4, 28, "glyph.pause", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphInbox, 4, 29, "glyph.inbox", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSpeaker, 4, 30, "glyph.speaker", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMute, 4, 31, "glyph.mute", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSliders, 4, 32, "glyph.sliders", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GaugeFill, 5, 3, "gauge.fill", "gauge", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphYoutube, 5, 24, "glyph.youtube", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTwitter, 5, 25, "glyph.twitter", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphFacebook, 5, 26, "glyph.facebook", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphGhost, 5, 27, "glyph.ghost", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphEdit, 5, 28, "glyph.edit", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCart, 5, 29, "glyph.cart", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonRefreshNormal, 5, 34, "button.refresh.normal", "button", "confirmed", "button.refresh.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonRefreshHover, 5, 35, "button.refresh.hover", "button", "confirmed", "button.refresh.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonRefreshPressed, 5, 36, "button.refresh.pressed", "button", "confirmed", "button.refresh.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowsVerticalNormal, 5, 37, "button.arrowsVertical.normal", "button", "confirmed", "button.arrowsVertical.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowsVerticalHover, 5, 38, "button.arrowsVertical.hover", "button", "confirmed", "button.arrowsVertical.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowsVerticalPressed, 5, 39, "button.arrowsVertical.pressed", "button", "confirmed", "button.arrowsVertical.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonPlayNormal, 5, 40, "button.play.normal", "button", "confirmed", "button.play.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonPlayHover, 5, 41, "button.play.hover", "button", "confirmed", "button.play.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonPlayPressed, 5, 42, "button.play.pressed", "button", "confirmed", "button.play.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMailNormal, 5, 43, "button.mail.normal", "button", "confirmed", "button.mail.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMailHover, 5, 44, "button.mail.hover", "button", "confirmed", "button.mail.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMailPressed, 5, 45, "button.mail.pressed", "button", "confirmed", "button.mail.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonFilterNormal, 5, 46, "button.filter.normal", "button", "confirmed", "button.filter.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonFilterHover, 5, 47, "button.filter.hover", "button", "confirmed", "button.filter.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonFilterPressed, 5, 48, "button.filter.pressed", "button", "confirmed", "button.filter.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.GlyphLockR6C24, 6, 24, "glyph.lock", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphLockOpenR6C25, 6, 25, "glyph.lockOpen", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphGridR6C26, 6, 26, "glyph.grid", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphBackR6C27, 6, 27, "glyph.back", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTreeR6C28, 6, 28, "glyph.tree", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphDiamondR6C29, 6, 29, "glyph.diamond", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphHomeR6C30, 6, 30, "glyph.home", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphListR6C31, 6, 31, "glyph.list", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTrashR6C32, 6, 32, "glyph.trash", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCheckR7C24, 7, 24, "glyph.check", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCrossR7C25, 7, 25, "glyph.cross", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPlusR7C26, 7, 26, "glyph.plus", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMinusR7C27, 7, 27, "glyph.minus", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowRightR7C28, 7, 28, "glyph.arrowRight", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowLeftR7C29, 7, 29, "glyph.arrowLeft", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowDownR7C30, 7, 30, "glyph.arrowDown", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowUpR7C31, 7, 31, "glyph.arrowUp", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphListAddR7C32, 7, 32, "glyph.listAdd", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonUserNormal, 7, 34, "button.user.normal", "button", "confirmed", "button.user.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ToggleCheck, 7, 35, "toggle.check", "toggle", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonUserPressed, 7, 36, "button.user.pressed", "button", "confirmed", "button.user.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ToggleCross, 7, 37, "toggle.cross", "toggle", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonQuestionHover, 7, 38, "button.question.hover", "button", "confirmed", "button.question.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonQuestionPressed, 7, 39, "button.question.pressed", "button", "confirmed", "button.question.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonTrophyNormal, 7, 40, "button.trophy.normal", "button", "confirmed", "button.trophy.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonTrophyHover, 7, 41, "button.trophy.hover", "button", "confirmed", "button.trophy.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonTrophyPressed, 7, 42, "button.trophy.pressed", "button", "confirmed", "button.trophy.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonClockNormal, 7, 43, "button.clock.normal", "button", "confirmed", "button.clock.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonClockHover, 7, 44, "button.clock.hover", "button", "confirmed", "button.clock.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonClockPressed, 7, 45, "button.clock.pressed", "button", "confirmed", "button.clock.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonPlaySquareNormal, 7, 46, "button.playSquare.normal", "button", "confirmed", "button.playSquare.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonPlaySquareHover, 7, 47, "button.playSquare.hover", "button", "confirmed", "button.playSquare.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonPlaySquarePressed, 7, 48, "button.playSquare.pressed", "button", "confirmed", "button.playSquare.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.StatusPhone, 8, 8, "status.phone", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusPawnGreen, 8, 9, "status.pawnGreen", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusPawnYellow, 8, 10, "status.pawnYellow", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusPawnRed, 8, 11, "status.pawnRed", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusGemDark, 8, 12, "status.gemDark", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusGemDarkSmall, 8, 13, "status.gemDarkSmall", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusGemDarkMini, 8, 14, "status.gemDarkMini", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphRefreshR8C24, 8, 24, "glyph.refresh", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowsVerticalR8C25, 8, 25, "glyph.arrowsVertical", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPlayR8C26, 8, 26, "glyph.play", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMailR8C27, 8, 27, "glyph.mail", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPlaySmallR8C28, 8, 28, "glyph.playSmall", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPreviousSmallR8C29, 8, 29, "glyph.previousSmall", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTriangleDownR8C30, 8, 30, "glyph.triangleDown", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTriangleUpR8C31, 8, 31, "glyph.triangleUp", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphFilterR8C32, 8, 32, "glyph.filter", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonRefresh, 8, 35, "button.refresh", "button", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusHourglassSmall, 9, 8, "status.hourglassSmall", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusGemPink, 9, 9, "status.gemPink", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusGemYellow, 9, 10, "status.gemYellow", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusGemRed, 9, 11, "status.gemRed", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusWoodHandle, 9, 12, "status.woodHandle", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusBoneHandle, 9, 13, "status.boneHandle", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusSilverHandle, 9, 14, "status.silverHandle", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphUserR9C24, 9, 24, "glyph.user", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphQuestionR9C25, 9, 25, "glyph.question", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTrophyR9C26, 9, 26, "glyph.trophy", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphClockR9C27, 9, 27, "glyph.clock", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPauseR9C28, 9, 28, "glyph.pause", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphInboxR9C29, 9, 29, "glyph.inbox", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSpeakerR9C30, 9, 30, "glyph.speaker", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMuteR9C31, 9, 31, "glyph.mute", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSlidersR9C32, 9, 32, "glyph.sliders", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonTreeNormal, 9, 34, "button.tree.normal", "button", "confirmed", "button.tree.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonTreeHover, 9, 35, "button.tree.hover", "button", "confirmed", "button.tree.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonTreePressed, 9, 36, "button.tree.pressed", "button", "confirmed", "button.tree.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonDiamondNormal, 9, 37, "button.diamond.normal", "button", "confirmed", "button.diamond.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonDiamondHover, 9, 38, "button.diamond.hover", "button", "confirmed", "button.diamond.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonDiamondPressed, 9, 39, "button.diamond.pressed", "button", "confirmed", "button.diamond.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonHomeNormal, 9, 40, "button.home.normal", "button", "confirmed", "button.home.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonHomeHover, 9, 41, "button.home.hover", "button", "confirmed", "button.home.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonHomePressed, 9, 42, "button.home.pressed", "button", "confirmed", "button.home.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonListNormal, 9, 43, "button.list.normal", "button", "confirmed", "button.list.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonListHover, 9, 44, "button.list.hover", "button", "confirmed", "button.list.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonListPressed, 9, 45, "button.list.pressed", "button", "confirmed", "button.list.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonTwitterNormal, 9, 46, "button.twitter.normal", "button", "confirmed", "button.twitter.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonTwitterHover, 9, 47, "button.twitter.hover", "button", "confirmed", "button.twitter.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonTwitterPressed, 9, 48, "button.twitter.pressed", "button", "confirmed", "button.twitter.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.StatusHourglass, 10, 8, "status.hourglass", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusBrain, 10, 9, "status.brain", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusEnergy, 10, 10, "status.energy", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusHeartSmall, 10, 11, "status.heartSmall", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusWoodHandleLong, 10, 12, "status.woodHandleLong", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.StatusHeartLarge, 10, 13, "status.heartLarge", "status", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphYoutubeR10C24, 10, 24, "glyph.youtube", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTwitterR10C25, 10, 25, "glyph.twitter", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphFacebookR10C26, 10, 26, "glyph.facebook", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphGhostR10C27, 10, 27, "glyph.ghost", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphEditR10C28, 10, 28, "glyph.edit", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCartR10C29, 10, 29, "glyph.cart", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonHome, 10, 34, "button.home", "button", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ItemBook, 11, 8, "item.book", "itemIcon", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonSettingsGear, 11, 10, "button.settingsGear", "button", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ItemDocument, 11, 12, "item.document", "itemIcon", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonArrowRightNormal, 11, 34, "button.arrowRight.normal", "direction", "confirmed", "button.arrowRight.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowRightHover, 11, 35, "button.arrowRight.hover", "direction", "confirmed", "button.arrowRight.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowRightPressed, 11, 36, "button.arrowRight.pressed", "direction", "confirmed", "button.arrowRight.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowLeftNormal, 11, 37, "button.arrowLeft.normal", "direction", "confirmed", "button.arrowLeft.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowLeftHover, 11, 38, "button.arrowLeft.hover", "direction", "confirmed", "button.arrowLeft.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowLeftPressed, 11, 39, "button.arrowLeft.pressed", "direction", "confirmed", "button.arrowLeft.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowDownNormal, 11, 40, "button.arrowDown.normal", "direction", "confirmed", "button.arrowDown.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowDownHover, 11, 41, "button.arrowDown.hover", "direction", "confirmed", "button.arrowDown.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowDownPressed, 11, 42, "button.arrowDown.pressed", "direction", "confirmed", "button.arrowDown.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowUpNormal, 11, 43, "button.arrowUp.normal", "direction", "confirmed", "button.arrowUp.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowUpHover, 11, 44, "button.arrowUp.hover", "direction", "confirmed", "button.arrowUp.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonArrowUpPressed, 11, 45, "button.arrowUp.pressed", "direction", "confirmed", "button.arrowUp.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonFacebookNormal, 11, 46, "button.facebook.normal", "button", "confirmed", "button.facebook.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonFacebookHover, 11, 47, "button.facebook.hover", "button", "confirmed", "button.facebook.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonFacebookPressed, 11, 48, "button.facebook.pressed", "button", "confirmed", "button.facebook.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonLock, 13, 24, "button.lock", "button", "probable", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonPlayNormalR13C34, 13, 34, "button.play.normal", "button", "confirmed", "button.play.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonPlayHoverR13C35, 13, 35, "button.play.hover", "button", "confirmed", "button.play.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonPlayPressedR13C36, 13, 36, "button.play.pressed", "button", "confirmed", "button.play.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonPreviousNormal, 13, 37, "button.previous.normal", "direction", "confirmed", "button.previous.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonPreviousHover, 13, 38, "button.previous.hover", "direction", "confirmed", "button.previous.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonPreviousPressed, 13, 39, "button.previous.pressed", "direction", "confirmed", "button.previous.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonTriangleDownNormal, 13, 40, "button.triangleDown.normal", "direction", "confirmed", "button.triangleDown.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonTriangleDownHover, 13, 41, "button.triangleDown.hover", "direction", "confirmed", "button.triangleDown.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonTriangleDownPressed, 13, 42, "button.triangleDown.pressed", "direction", "confirmed", "button.triangleDown.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonTriangleUpNormal, 13, 43, "button.triangleUp.normal", "direction", "confirmed", "button.triangleUp.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonTriangleUpHover, 13, 44, "button.triangleUp.hover", "direction", "confirmed", "button.triangleUp.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonTriangleUpPressed, 13, 45, "button.triangleUp.pressed", "direction", "confirmed", "button.triangleUp.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonGhostNormal, 13, 46, "button.ghost.normal", "button", "confirmed", "button.ghost.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonGhostHover, 13, 47, "button.ghost.hover", "button", "confirmed", "button.ghost.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonGhostPressed, 13, 48, "button.ghost.pressed", "button", "confirmed", "button.ghost.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphLock, 15, 24, "buttonGlyph.lock", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphLockOpen, 15, 25, "buttonGlyph.lockOpen", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphGrid, 15, 26, "buttonGlyph.grid", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphBack, 15, 27, "buttonGlyph.back", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphTree, 15, 28, "buttonGlyph.tree", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphDiamond, 15, 29, "buttonGlyph.diamond", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphHome, 15, 30, "buttonGlyph.home", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphList, 15, 31, "buttonGlyph.list", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphTrash, 15, 32, "buttonGlyph.trash", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonPauseNormal, 15, 34, "button.pause.normal", "button", "confirmed", "button.pause.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonPauseHover, 15, 35, "button.pause.hover", "button", "confirmed", "button.pause.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonPausePressed, 15, 36, "button.pause.pressed", "button", "confirmed", "button.pause.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonInboxNormal, 15, 37, "button.inbox.normal", "button", "confirmed", "button.inbox.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonInboxHover, 15, 38, "button.inbox.hover", "button", "confirmed", "button.inbox.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonInboxPressed, 15, 39, "button.inbox.pressed", "button", "confirmed", "button.inbox.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonSpeakerNormal, 15, 40, "button.speaker.normal", "button", "confirmed", "button.speaker.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonSpeakerHover, 15, 41, "button.speaker.hover", "button", "confirmed", "button.speaker.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonSpeakerPressed, 15, 42, "button.speaker.pressed", "button", "confirmed", "button.speaker.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMuteNormal, 15, 43, "button.mute.normal", "button", "confirmed", "button.mute.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMuteHover, 15, 44, "button.mute.hover", "button", "confirmed", "button.mute.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMutePressed, 15, 45, "button.mute.pressed", "button", "confirmed", "button.mute.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonTrashNormal, 15, 46, "button.trash.normal", "button", "confirmed", "button.trash.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonTrashHover, 15, 47, "button.trash.hover", "button", "confirmed", "button.trash.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonTrashPressed, 15, 48, "button.trash.pressed", "button", "confirmed", "button.trash.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphCheck, 16, 24, "buttonGlyph.check", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphCross, 16, 25, "buttonGlyph.cross", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphPlus, 16, 26, "buttonGlyph.plus", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphMinus, 16, 27, "buttonGlyph.minus", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphArrowRight, 16, 28, "buttonGlyph.arrowRight", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphArrowLeft, 16, 29, "buttonGlyph.arrowLeft", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphArrowDown, 16, 30, "buttonGlyph.arrowDown", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphArrowUp, 16, 31, "buttonGlyph.arrowUp", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphListAdd, 16, 32, "buttonGlyph.listAdd", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphRefresh, 17, 24, "buttonGlyph.refresh", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphArrowsVertical, 17, 25, "buttonGlyph.arrowsVertical", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphPlay, 17, 26, "buttonGlyph.play", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphMail, 17, 27, "buttonGlyph.mail", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphPlaySmall, 17, 28, "buttonGlyph.playSmall", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphPreviousSmall, 17, 29, "buttonGlyph.previousSmall", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphTriangleDown, 17, 30, "buttonGlyph.triangleDown", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphTriangleUp, 17, 31, "buttonGlyph.triangleUp", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonGlyphFilter, 17, 32, "buttonGlyph.filter", "button", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphUserR18C24, 18, 24, "glyph.user", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphQuestionR18C25, 18, 25, "glyph.question", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTrophyR18C26, 18, 26, "glyph.trophy", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphClockR18C27, 18, 27, "glyph.clock", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPauseR18C28, 18, 28, "glyph.pause", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphInboxR18C29, 18, 29, "glyph.inbox", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSpeakerR18C30, 18, 30, "glyph.speaker", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMuteR18C31, 18, 31, "glyph.mute", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSlidersR18C32, 18, 32, "glyph.sliders", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphYoutubeR19C24, 19, 24, "glyph.youtube", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTwitterR19C25, 19, 25, "glyph.twitter", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphFacebookR19C26, 19, 26, "glyph.facebook", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphGhostR19C27, 19, 27, "glyph.ghost", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphEditR19C28, 19, 28, "glyph.edit", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCartR19C29, 19, 29, "glyph.cart", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.CursorPointerLarge, 20, 10, "cursor.pointerLarge", "cursor", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.CursorPointerFeather, 20, 11, "cursor.pointerFeather", "cursor", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.CursorHandOpen, 20, 12, "cursor.handOpen", "cursor", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.CursorHandClosed, 20, 13, "cursor.handClosed", "cursor", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.CursorTrianglePointer, 20, 14, "cursor.trianglePointer", "cursor", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphLockR20C24, 20, 24, "glyph.lock", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphLockOpenR20C25, 20, 25, "glyph.lockOpen", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphGridR20C26, 20, 26, "glyph.grid", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphBackR20C27, 20, 27, "glyph.back", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTreeR20C28, 20, 28, "glyph.tree", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphDiamondR20C29, 20, 29, "glyph.diamond", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphHomeR20C30, 20, 30, "glyph.home", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphListR20C31, 20, 31, "glyph.list", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTrashR20C32, 20, 32, "glyph.trash", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.CursorPointerLargeAlt, 21, 10, "cursor.pointerLargeAlt", "cursor", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.CursorHandPoint, 21, 11, "cursor.handPoint", "cursor", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.CursorHandGrab, 21, 12, "cursor.handGrab", "cursor", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.CursorHandClick, 21, 13, "cursor.handClick", "cursor", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCheckR21C24, 21, 24, "glyph.check", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCrossR21C25, 21, 25, "glyph.cross", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPlusR21C26, 21, 26, "glyph.plus", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMinusR21C27, 21, 27, "glyph.minus", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowRightR21C28, 21, 28, "glyph.arrowRight", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowLeftR21C29, 21, 29, "glyph.arrowLeft", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowDownR21C30, 21, 30, "glyph.arrowDown", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowUpR21C31, 21, 31, "glyph.arrowUp", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphListAddR21C32, 21, 32, "glyph.listAdd", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ToggleCrossLarge, 22, 8, "toggle.crossLarge", "toggle", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ToggleCrossLargeAlt, 22, 9, "toggle.crossLargeAlt", "toggle", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ToggleCrossSmall, 22, 10, "toggle.crossSmall", "toggle", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ToggleCrossSmallAlt, 22, 11, "toggle.crossSmallAlt", "toggle", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphRefreshR22C24, 22, 24, "glyph.refresh", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphArrowsVerticalR22C25, 22, 25, "glyph.arrowsVertical", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPlayR22C26, 22, 26, "glyph.play", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMailR22C27, 22, 27, "glyph.mail", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPlaySmallR22C28, 22, 28, "glyph.playSmall", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPreviousSmallR22C29, 22, 29, "glyph.previousSmall", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTriangleDownR22C30, 22, 30, "glyph.triangleDown", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTriangleUpR22C31, 22, 31, "glyph.triangleUp", "direction", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphFilterR22C32, 22, 32, "glyph.filter", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ToggleCheckLarge, 23, 8, "toggle.checkLarge", "toggle", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ToggleCheckLargeAlt, 23, 9, "toggle.checkLargeAlt", "toggle", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ToggleCheckSmall, 23, 10, "toggle.checkSmall", "toggle", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ToggleCheckSmallAlt, 23, 11, "toggle.checkSmallAlt", "toggle", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphUserR23C24, 23, 24, "glyph.user", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphQuestionR23C25, 23, 25, "glyph.question", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTrophyR23C26, 23, 26, "glyph.trophy", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphClockR23C27, 23, 27, "glyph.clock", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphPauseR23C28, 23, 28, "glyph.pause", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphInboxR23C29, 23, 29, "glyph.inbox", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSpeakerR23C30, 23, 30, "glyph.speaker", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphMuteR23C31, 23, 31, "glyph.mute", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphSlidersR23C32, 23, 32, "glyph.sliders", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphYoutubeR24C24, 24, 24, "glyph.youtube", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphTwitterR24C25, 24, 25, "glyph.twitter", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphFacebookR24C26, 24, 26, "glyph.facebook", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphGhostR24C27, 24, 27, "glyph.ghost", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphEditR24C28, 24, 28, "glyph.edit", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.GlyphCartR24C29, 24, 29, "glyph.cart", "controlGlyph", "confirmed", null, null),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixLockNormal, 25, 24, "buttonMatrix.lock.normal", "button", "confirmed", "buttonMatrix.lock.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixLockHover, 25, 25, "buttonMatrix.lock.hover", "button", "confirmed", "buttonMatrix.lock.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixLockPressed, 25, 26, "buttonMatrix.lock.pressed", "button", "confirmed", "buttonMatrix.lock.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixLockOpenNormal, 25, 27, "buttonMatrix.lockOpen.normal", "button", "confirmed", "buttonMatrix.lockOpen.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixLockOpenHover, 25, 28, "buttonMatrix.lockOpen.hover", "button", "confirmed", "buttonMatrix.lockOpen.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixLockOpenPressed, 25, 29, "buttonMatrix.lockOpen.pressed", "button", "confirmed", "buttonMatrix.lockOpen.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixGridNormal, 25, 30, "buttonMatrix.grid.normal", "button", "confirmed", "buttonMatrix.grid.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixGridHover, 25, 31, "buttonMatrix.grid.hover", "button", "confirmed", "buttonMatrix.grid.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixGridPressed, 25, 32, "buttonMatrix.grid.pressed", "button", "confirmed", "buttonMatrix.grid.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixBackNormal, 25, 33, "buttonMatrix.back.normal", "button", "confirmed", "buttonMatrix.back.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixBackHover, 25, 34, "buttonMatrix.back.hover", "button", "confirmed", "buttonMatrix.back.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixBackPressed, 25, 35, "buttonMatrix.back.pressed", "button", "confirmed", "buttonMatrix.back.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixEditNormal, 25, 36, "buttonMatrix.edit.normal", "button", "confirmed", "buttonMatrix.edit.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixEditHover, 25, 37, "buttonMatrix.edit.hover", "button", "confirmed", "buttonMatrix.edit.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixEditPressed, 25, 38, "buttonMatrix.edit.pressed", "button", "confirmed", "buttonMatrix.edit.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTrashNormal, 25, 39, "buttonMatrix.trash.normal", "button", "confirmed", "buttonMatrix.trash.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTrashHover, 25, 40, "buttonMatrix.trash.hover", "button", "confirmed", "buttonMatrix.trash.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTrashPressed, 25, 41, "buttonMatrix.trash.pressed", "button", "confirmed", "buttonMatrix.trash.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixListAddNormal, 25, 42, "buttonMatrix.listAdd.normal", "button", "confirmed", "buttonMatrix.listAdd.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixListAddHover, 25, 43, "buttonMatrix.listAdd.hover", "button", "confirmed", "buttonMatrix.listAdd.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixListAddPressed, 25, 44, "buttonMatrix.listAdd.pressed", "button", "confirmed", "buttonMatrix.listAdd.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixCheckNormal, 26, 24, "buttonMatrix.check.normal", "button", "confirmed", "buttonMatrix.check.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixCheckHover, 26, 25, "buttonMatrix.check.hover", "button", "confirmed", "buttonMatrix.check.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixCheckPressed, 26, 26, "buttonMatrix.check.pressed", "button", "confirmed", "buttonMatrix.check.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixCrossNormal, 26, 27, "buttonMatrix.cross.normal", "button", "confirmed", "buttonMatrix.cross.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixCrossHover, 26, 28, "buttonMatrix.cross.hover", "button", "confirmed", "buttonMatrix.cross.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixCrossPressed, 26, 29, "buttonMatrix.cross.pressed", "button", "confirmed", "buttonMatrix.cross.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlusNormal, 26, 30, "buttonMatrix.plus.normal", "button", "confirmed", "buttonMatrix.plus.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlusHover, 26, 31, "buttonMatrix.plus.hover", "button", "confirmed", "buttonMatrix.plus.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlusPressed, 26, 32, "buttonMatrix.plus.pressed", "button", "confirmed", "buttonMatrix.plus.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixMinusNormal, 26, 33, "buttonMatrix.minus.normal", "button", "confirmed", "buttonMatrix.minus.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixMinusHover, 26, 34, "buttonMatrix.minus.hover", "button", "confirmed", "buttonMatrix.minus.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixMinusPressed, 26, 35, "buttonMatrix.minus.pressed", "button", "confirmed", "buttonMatrix.minus.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixEditNormalR26C36, 26, 36, "buttonMatrix.edit.normal", "button", "confirmed", "buttonMatrix.edit.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixEditHoverR26C37, 26, 37, "buttonMatrix.edit.hover", "button", "confirmed", "buttonMatrix.edit.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixEditPressedR26C38, 26, 38, "buttonMatrix.edit.pressed", "button", "confirmed", "buttonMatrix.edit.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTrashNormalR26C39, 26, 39, "buttonMatrix.trash.normal", "button", "confirmed", "buttonMatrix.trash.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTrashHoverR26C40, 26, 40, "buttonMatrix.trash.hover", "button", "confirmed", "buttonMatrix.trash.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTrashPressedR26C41, 26, 41, "buttonMatrix.trash.pressed", "button", "confirmed", "buttonMatrix.trash.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixListAddNormalR26C42, 26, 42, "buttonMatrix.listAdd.normal", "button", "confirmed", "buttonMatrix.listAdd.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixListAddHoverR26C43, 26, 43, "buttonMatrix.listAdd.hover", "button", "confirmed", "buttonMatrix.listAdd.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixListAddPressedR26C44, 26, 44, "buttonMatrix.listAdd.pressed", "button", "confirmed", "buttonMatrix.listAdd.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixRefreshNormal, 27, 24, "buttonMatrix.refresh.normal", "button", "confirmed", "buttonMatrix.refresh.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixRefreshHover, 27, 25, "buttonMatrix.refresh.hover", "button", "confirmed", "buttonMatrix.refresh.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixRefreshPressed, 27, 26, "buttonMatrix.refresh.pressed", "button", "confirmed", "buttonMatrix.refresh.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowsVerticalNormal, 27, 27, "buttonMatrix.arrowsVertical.normal", "button", "confirmed", "buttonMatrix.arrowsVertical.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowsVerticalHover, 27, 28, "buttonMatrix.arrowsVertical.hover", "button", "confirmed", "buttonMatrix.arrowsVertical.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowsVerticalPressed, 27, 29, "buttonMatrix.arrowsVertical.pressed", "button", "confirmed", "buttonMatrix.arrowsVertical.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlayNormal, 27, 30, "buttonMatrix.play.normal", "button", "confirmed", "buttonMatrix.play.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlayHover, 27, 31, "buttonMatrix.play.hover", "button", "confirmed", "buttonMatrix.play.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlayPressed, 27, 32, "buttonMatrix.play.pressed", "button", "confirmed", "buttonMatrix.play.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixMailNormal, 27, 33, "buttonMatrix.mail.normal", "button", "confirmed", "buttonMatrix.mail.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixMailHover, 27, 34, "buttonMatrix.mail.hover", "button", "confirmed", "buttonMatrix.mail.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixMailPressed, 27, 35, "buttonMatrix.mail.pressed", "button", "confirmed", "buttonMatrix.mail.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixClockNormal, 27, 36, "buttonMatrix.clock.normal", "button", "confirmed", "buttonMatrix.clock.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixClockHover, 27, 37, "buttonMatrix.clock.hover", "button", "confirmed", "buttonMatrix.clock.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixClockPressed, 27, 38, "buttonMatrix.clock.pressed", "button", "confirmed", "buttonMatrix.clock.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixFilterNormal, 27, 39, "buttonMatrix.filter.normal", "button", "confirmed", "buttonMatrix.filter.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixFilterHover, 27, 40, "buttonMatrix.filter.hover", "button", "confirmed", "buttonMatrix.filter.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixFilterPressed, 27, 41, "buttonMatrix.filter.pressed", "button", "confirmed", "buttonMatrix.filter.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixUserNormal, 28, 24, "buttonMatrix.user.normal", "button", "confirmed", "buttonMatrix.user.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixUserHover, 28, 25, "buttonMatrix.user.hover", "button", "confirmed", "buttonMatrix.user.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixUserPressed, 28, 26, "buttonMatrix.user.pressed", "button", "confirmed", "buttonMatrix.user.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixQuestionNormal, 28, 27, "buttonMatrix.question.normal", "button", "confirmed", "buttonMatrix.question.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixQuestionHover, 28, 28, "buttonMatrix.question.hover", "button", "confirmed", "buttonMatrix.question.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixQuestionPressed, 28, 29, "buttonMatrix.question.pressed", "button", "confirmed", "buttonMatrix.question.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTrophyNormal, 28, 30, "buttonMatrix.trophy.normal", "button", "confirmed", "buttonMatrix.trophy.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTrophyHover, 28, 31, "buttonMatrix.trophy.hover", "button", "confirmed", "buttonMatrix.trophy.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTrophyPressed, 28, 32, "buttonMatrix.trophy.pressed", "button", "confirmed", "buttonMatrix.trophy.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixClockNormalR28C33, 28, 33, "buttonMatrix.clock.normal", "button", "confirmed", "buttonMatrix.clock.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixClockHoverR28C34, 28, 34, "buttonMatrix.clock.hover", "button", "confirmed", "buttonMatrix.clock.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixClockPressedR28C35, 28, 35, "buttonMatrix.clock.pressed", "button", "confirmed", "buttonMatrix.clock.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixFilterNormalR28C36, 28, 36, "buttonMatrix.filter.normal", "button", "confirmed", "buttonMatrix.filter.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixFilterHoverR28C37, 28, 37, "buttonMatrix.filter.hover", "button", "confirmed", "buttonMatrix.filter.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixFilterPressedR28C38, 28, 38, "buttonMatrix.filter.pressed", "button", "confirmed", "buttonMatrix.filter.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixYoutubeNormal, 29, 24, "buttonMatrix.youtube.normal", "button", "confirmed", "buttonMatrix.youtube.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixYoutubeHover, 29, 25, "buttonMatrix.youtube.hover", "button", "confirmed", "buttonMatrix.youtube.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixYoutubePressed, 29, 26, "buttonMatrix.youtube.pressed", "button", "confirmed", "buttonMatrix.youtube.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTwitterNormal, 29, 27, "buttonMatrix.twitter.normal", "button", "confirmed", "buttonMatrix.twitter.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTwitterHover, 29, 28, "buttonMatrix.twitter.hover", "button", "confirmed", "buttonMatrix.twitter.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTwitterPressed, 29, 29, "buttonMatrix.twitter.pressed", "button", "confirmed", "buttonMatrix.twitter.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixFacebookNormal, 29, 30, "buttonMatrix.facebook.normal", "button", "confirmed", "buttonMatrix.facebook.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixFacebookHover, 29, 31, "buttonMatrix.facebook.hover", "button", "confirmed", "buttonMatrix.facebook.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixFacebookPressed, 29, 32, "buttonMatrix.facebook.pressed", "button", "confirmed", "buttonMatrix.facebook.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixGhostNormal, 29, 33, "buttonMatrix.ghost.normal", "button", "confirmed", "buttonMatrix.ghost.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixGhostHover, 29, 34, "buttonMatrix.ghost.hover", "button", "confirmed", "buttonMatrix.ghost.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixGhostPressed, 29, 35, "buttonMatrix.ghost.pressed", "button", "confirmed", "buttonMatrix.ghost.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixSlidersNormal, 29, 36, "buttonMatrix.sliders.normal", "button", "confirmed", "buttonMatrix.sliders.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixSlidersHover, 29, 37, "buttonMatrix.sliders.hover", "button", "confirmed", "buttonMatrix.sliders.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixSlidersPressed, 29, 38, "buttonMatrix.sliders.pressed", "button", "confirmed", "buttonMatrix.sliders.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTreeNormal, 30, 24, "buttonMatrix.tree.normal", "button", "confirmed", "buttonMatrix.tree.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTreeHover, 30, 25, "buttonMatrix.tree.hover", "button", "confirmed", "buttonMatrix.tree.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTreePressed, 30, 26, "buttonMatrix.tree.pressed", "button", "confirmed", "buttonMatrix.tree.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixDiamondNormal, 30, 27, "buttonMatrix.diamond.normal", "button", "confirmed", "buttonMatrix.diamond.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixDiamondHover, 30, 28, "buttonMatrix.diamond.hover", "button", "confirmed", "buttonMatrix.diamond.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixDiamondPressed, 30, 29, "buttonMatrix.diamond.pressed", "button", "confirmed", "buttonMatrix.diamond.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixHomeNormal, 30, 30, "buttonMatrix.home.normal", "button", "confirmed", "buttonMatrix.home.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixHomeHover, 30, 31, "buttonMatrix.home.hover", "button", "confirmed", "buttonMatrix.home.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixHomePressed, 30, 32, "buttonMatrix.home.pressed", "button", "confirmed", "buttonMatrix.home.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixListNormal, 30, 33, "buttonMatrix.list.normal", "button", "confirmed", "buttonMatrix.list.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixListHover, 30, 34, "buttonMatrix.list.hover", "button", "confirmed", "buttonMatrix.list.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixListPressed, 30, 35, "buttonMatrix.list.pressed", "button", "confirmed", "buttonMatrix.list.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixCartNormal, 30, 36, "buttonMatrix.cart.normal", "button", "confirmed", "buttonMatrix.cart.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixCartHover, 30, 37, "buttonMatrix.cart.hover", "button", "confirmed", "buttonMatrix.cart.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixCartPressed, 30, 38, "buttonMatrix.cart.pressed", "button", "confirmed", "buttonMatrix.cart.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowRightNormal, 31, 24, "buttonMatrix.arrowRight.normal", "direction", "confirmed", "buttonMatrix.arrowRight.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowRightHover, 31, 25, "buttonMatrix.arrowRight.hover", "direction", "confirmed", "buttonMatrix.arrowRight.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowRightPressed, 31, 26, "buttonMatrix.arrowRight.pressed", "direction", "confirmed", "buttonMatrix.arrowRight.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowLeftNormal, 31, 27, "buttonMatrix.arrowLeft.normal", "direction", "confirmed", "buttonMatrix.arrowLeft.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowLeftHover, 31, 28, "buttonMatrix.arrowLeft.hover", "direction", "confirmed", "buttonMatrix.arrowLeft.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowLeftPressed, 31, 29, "buttonMatrix.arrowLeft.pressed", "direction", "confirmed", "buttonMatrix.arrowLeft.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowDownNormal, 31, 30, "buttonMatrix.arrowDown.normal", "direction", "confirmed", "buttonMatrix.arrowDown.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowDownHover, 31, 31, "buttonMatrix.arrowDown.hover", "direction", "confirmed", "buttonMatrix.arrowDown.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowDownPressed, 31, 32, "buttonMatrix.arrowDown.pressed", "direction", "confirmed", "buttonMatrix.arrowDown.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowUpNormal, 31, 33, "buttonMatrix.arrowUp.normal", "direction", "confirmed", "buttonMatrix.arrowUp.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowUpHover, 31, 34, "buttonMatrix.arrowUp.hover", "direction", "confirmed", "buttonMatrix.arrowUp.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixArrowUpPressed, 31, 35, "buttonMatrix.arrowUp.pressed", "direction", "confirmed", "buttonMatrix.arrowUp.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlayNormalR32C24, 32, 24, "buttonMatrix.play.normal", "button", "confirmed", "buttonMatrix.play.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlayHoverR32C25, 32, 25, "buttonMatrix.play.hover", "button", "confirmed", "buttonMatrix.play.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPlayPressedR32C26, 32, 26, "buttonMatrix.play.pressed", "button", "confirmed", "buttonMatrix.play.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPreviousNormal, 32, 27, "buttonMatrix.previous.normal", "direction", "confirmed", "buttonMatrix.previous.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPreviousHover, 32, 28, "buttonMatrix.previous.hover", "direction", "confirmed", "buttonMatrix.previous.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPreviousPressed, 32, 29, "buttonMatrix.previous.pressed", "direction", "confirmed", "buttonMatrix.previous.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTriangleDownNormal, 32, 30, "buttonMatrix.triangleDown.normal", "direction", "confirmed", "buttonMatrix.triangleDown.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTriangleDownHover, 32, 31, "buttonMatrix.triangleDown.hover", "direction", "confirmed", "buttonMatrix.triangleDown.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTriangleDownPressed, 32, 32, "buttonMatrix.triangleDown.pressed", "direction", "confirmed", "buttonMatrix.triangleDown.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTriangleUpNormal, 32, 33, "buttonMatrix.triangleUp.normal", "direction", "confirmed", "buttonMatrix.triangleUp.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTriangleUpHover, 32, 34, "buttonMatrix.triangleUp.hover", "direction", "confirmed", "buttonMatrix.triangleUp.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixTriangleUpPressed, 32, 35, "buttonMatrix.triangleUp.pressed", "direction", "confirmed", "buttonMatrix.triangleUp.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPauseNormal, 33, 24, "buttonMatrix.pause.normal", "button", "confirmed", "buttonMatrix.pause.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPauseHover, 33, 25, "buttonMatrix.pause.hover", "button", "confirmed", "buttonMatrix.pause.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixPausePressed, 33, 26, "buttonMatrix.pause.pressed", "button", "confirmed", "buttonMatrix.pause.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixInboxNormal, 33, 27, "buttonMatrix.inbox.normal", "button", "confirmed", "buttonMatrix.inbox.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixInboxHover, 33, 28, "buttonMatrix.inbox.hover", "button", "confirmed", "buttonMatrix.inbox.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixInboxPressed, 33, 29, "buttonMatrix.inbox.pressed", "button", "confirmed", "buttonMatrix.inbox.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixSpeakerNormal, 33, 30, "buttonMatrix.speaker.normal", "button", "confirmed", "buttonMatrix.speaker.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixSpeakerHover, 33, 31, "buttonMatrix.speaker.hover", "button", "confirmed", "buttonMatrix.speaker.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixSpeakerPressed, 33, 32, "buttonMatrix.speaker.pressed", "button", "confirmed", "buttonMatrix.speaker.state", "pressed"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixMuteNormal, 33, 33, "buttonMatrix.mute.normal", "button", "confirmed", "buttonMatrix.mute.state", "normal"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixMuteHover, 33, 34, "buttonMatrix.mute.hover", "button", "confirmed", "buttonMatrix.mute.state", "hover"),
            EntryFor(ModernUiStyle2Icon.ButtonMatrixMutePressed, 33, 35, "buttonMatrix.mute.pressed", "button", "confirmed", "buttonMatrix.mute.state", "pressed"),
        };

        public static ModernUiSpriteKey GetSpriteKey(ModernUiStyle2Icon icon)
        {
            foreach (Entry entry in Entries)
            {
                if (entry.Icon == icon)
                {
                    return entry.SpriteKey;
                }
            }

            throw new ArgumentOutOfRangeException(nameof(icon), icon, "Unknown Modern UI Style2 icon.");
        }

        private static Entry EntryFor(ModernUiStyle2Icon icon, int row, int column, string semanticId, string category, string confidence, string stateGroupId, string stateRole)
        {
            string coordinate = "r" + row + "_c" + column;
            string spriteName = Prefix + coordinate;
            return new Entry(icon, row, column, coordinate, spriteName, semanticId, category, stateGroupId, stateRole, confidence);
        }

        public readonly struct Entry
        {
            public Entry(ModernUiStyle2Icon icon, int row, int column, string coordinate, string spriteName, string semanticId, string category, string stateGroupId, string stateRole, string confidence)
            {
                Icon = icon;
                Row = row;
                Column = column;
                Coordinate = coordinate;
                SpriteName = spriteName;
                SemanticId = semanticId;
                Category = category;
                StateGroupId = stateGroupId;
                StateRole = stateRole;
                Confidence = confidence;
                SpriteKey = new ModernUiSpriteKey(ModernUiStyle2Sprites.SheetAddress, spriteName, row, column, semanticId);
            }

            public ModernUiStyle2Icon Icon { get; }
            public int Row { get; }
            public int Column { get; }
            public string Coordinate { get; }
            public string SpriteName { get; }
            public string SemanticId { get; }
            public string Category { get; }
            public string StateGroupId { get; }
            public string StateRole { get; }
            public string Confidence { get; }
            public ModernUiSpriteKey SpriteKey { get; }
        }
    }
}
